pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Assemble') {
            steps {
                dir('CE2/gradle-basic-demo') {
                    sh 'chmod +x gradlew'
                    sh './gradlew assemble'
                }
            }
        }

        stage('Test') {
            steps {
                dir('CE2/gradle-basic-demo') {
                    sh './gradlew test'
                }
                junit allowEmptyResults: true, testResults: 'CE2/gradle-basic-demo/build/test-results/test/*.xml'
            }
        }

        stage('Archive') {
            steps {
                archiveArtifacts 'CE2/gradle-basic-demo/build/libs/*.jar'
            }
        }
    }
}