Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-22.04"

    config.vm.define "ansible" do |ansible|
        ansible.vm.hostname = "ansible"
        ansible.vm.network "private_network", ip: "192.168.56.9"
        ansible.ssh.forward_agent = true

        ansible.vm.synced_folder ".", "/vagrant", mount_options: ["dmode=775,fmode=600"]

        ansible.vm.provider "virtualbox" do |vb|
            vb.memory = 2048
            vb.cpus = 2
        end

        ansible.vm.provision "file",
            source: File.expand_path("~/.vagrant.d/insecure_private_key"),
            destination: "/home/vagrant/.ssh/id_rsa"

        ansible.vm.provision "shell", inline: <<-SHELL
            mkdir -p /home/vagrant/.ssh
            chmod 700 /home/vagrant/.ssh
            chmod 600 /home/vagrant/.ssh/id_rsa
            chown -R vagrant:vagrant /home/vagrant/.ssh
            export DEBIAN_FRONTEND=noninteractive
            apt-get update --yes
            apt-get install --yes software-properties-common
            apt-add-repository --yes ppa:ansible/ansible
            apt-get update --yes
            apt-get install --yes ansible
        SHELL
    end

    config.vm.define "app" do |app|
        app.vm.hostname = "app"
        app.vm.network "private_network", ip: "192.168.56.10"
        app.vm.network "forwarded_port", guest: 8080, host: 8080

        app.vm.provider "virtualbox" do |vb|
            vb.memory = 4096
            vb.cpus = 2
        end

        app.vm.provision "shell", inline: <<-SHELL
            export DEBIAN_FRONTEND=noninteractive
            apt-get update --yes
            apt-get install --yes python3
        SHELL
    end

    config.vm.define "h2" do |h2|
        h2.vm.hostname = "h2"
        h2.vm.network "private_network", ip: "192.168.56.11"
        h2.vm.network "forwarded_port", guest: 8082, host: 8082

        h2.vm.provider "virtualbox" do |vb|
            vb.memory = 2048
            vb.cpus = 1
        end

        h2.vm.provision "shell", inline: <<-SHELL
            export DEBIAN_FRONTEND=noninteractive
            apt-get update --yes
            apt-get install --yes python3
        SHELL
    end
end