pipeline {
    agent {
        docker {
            image 'gradle:7.4.2-jdk11'
        }
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Java Version') {
            steps {
                sh 'java -version'
                sh './gradlew --version'
            }
        }

        stage('Assemble') {
            steps {
                dir('CE2/basic') {
                    sh 'chmod +x gradlew'
                    sh './gradlew assemble'
                }
            }
        }

        stage('Test') {
            steps {
                dir('CE2/basic') {
                    sh './gradlew test'
                }
                junit allowEmptyResults: true, testResults: 'CE2/basic/build/test-results/test/*.xml'
            }
        }

        stage('Javadoc') {
            steps {
                dir('CE2/basic') {
                    sh './gradlew javadoc'
                }
            }
        }

        stage('Archive') {
            steps {
                archiveArtifacts 'CE2/basic/build/libs/*.war'
            }
        }
    }
}