pipeline {
    agent {
        docker {
            image 'gradle:7.4.2-jdk11'
        }
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Java Version') {
            steps {
                dir('CE2/basic') {
                    sh 'java -version'
                    sh 'chmod +x gradlew'
                    sh './gradlew --version'
                }
            }
        }

        stage('Assemble') {
            steps {
                dir('CE2/basic') {
                    sh './gradlew assemble'
                }
            }
        }

        stage('Test') {
            steps {
                dir('CE2/basic') {
                    sh './gradlew test'
                }
            }
            post {
                always {
                    junit allowEmptyResults: true, testResults: 'CE2/basic/build/test-results/test/*.xml'
                }
            }
        }

        stage('Javadoc') {
            steps {
                dir('CE2/basic') {
                    sh './gradlew javadoc'
                }
            }
        }

        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'CE2/basic/build/libs/*.war', fingerprint: true
                archiveArtifacts artifacts: 'CE2/basic/build/docs/javadoc/**', fingerprint: true
            }
        }

        stage('Publish Image') {
            steps {
                dir('CE2/basic') {
                    sh '''
                        apt-get update
                        apt-get install -y docker.io
                        docker --version
                    '''
                    script {
                        docker.withRegistry('', 'dockerhub') {
                            def customImage = docker.build("gui1251991lemes/ce2-basic:${env.BUILD_NUMBER}")
                            customImage.push()
                            customImage.push('latest')
                        }
                    }
                }
            }
        }
    }
}